[pytest]
asyncio_mode = auto
addopts =
    --cov=fastapi_filter
    --cov-report=term-missing
filterwarnings =
  error
  ignore:Accessing the 'model_fields' attribute on the instance is deprecated:pydantic.warnings.PydanticDeprecatedSince211
