version: "3.3"

services:

  elasticsearch:
    image: elasticsearch:7.6.2
        # restart: always
    ports:
      - 9200:9200
    environment:
        - node.name=fastapi-filter-es
        - cluster.name=fastapi-filter-es-docker-cluster
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
            soft: -1
            hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  elasticsearch-data: